hyperledger/aries-framework-dotnet

- Directory.Build.props
- src/AgentFramework.AspNetCore/Middleware/AgentMiddleware.cs
Fixes an issue that occurs when working with non-web agents where response isn't fully sent back to the client. Affects users of return routing.
> Use response object to write data to stream instead stream copy

- nuget.config
- src/AgentFramework.Core.Handlers/Internal/DefaultProofHandler.cs
- src/AgentFramework.Core/Configuration/TxnAuthorAcceptanceHostedService.cs
- src/AgentFramework.Core/Contracts/ICredentialService.cs
- src/AgentFramework.Core/Contracts/ILedgerService.cs
- src/AgentFramework.Core/Contracts/IPoolService.cs
- src/AgentFramework.Core/Contracts/IProofService.cs
- src/AgentFramework.Core/Decorators/Signature/SignatureUtils.cs
- src/AgentFramework.Core/Extensions/FormattingExtensions.cs
- src/AgentFramework.Core/Messages/MessageType.cs
- src/AgentFramework.Core/Messages/MessageTypes.cs
- src/AgentFramework.Core/Messages/Proofs/PresentationMessage.cs
- src/AgentFramework.Core/Messages/Proofs/ProofMessage.cs
- src/AgentFramework.Core/Messages/Proofs/ProofRequestMessage.cs
- src/AgentFramework.Core/Messages/Proofs/RequestPresentationMessage.cs
- src/AgentFramework.Core/Runtime/DefaultCredentialService.cs
- src/AgentFramework.Core/Runtime/DefaultCredentialServiceV1.cs
- src/AgentFramework.Core/Runtime/DefaultLedgerService.cs
- src/AgentFramework.Core/Runtime/DefaultPoolService.cs
- src/AgentFramework.Core/Runtime/DefaultProofService.cs
- src/AgentFramework.TestHarness/AgentScenarios.cs
- src/AgentFramework.TestHarness/Scenarios.cs
- test/AgentFramework.Core.Tests/LerdgerTests.cs
- test/AgentFramework.Core.Tests/Protocols/CredentialTests.cs
- test/AgentFramework.Core.Tests/Protocols/ProofTests.cs
- Added Presentation Protocol v1. Old methods and models are marked Obsolete and will be removed soon.
- Moved Taa and Aml into Pool Service and added caching logic. Their values will be fetched from ledger only once per service lifetime.
- Updated Base64 extensions encoding to bring the codebase in line with the Aries RFC 0036
- Updated unit tests to test against Issue and Proof protocols v1
> Proof Protocol added. Issue Protocol fixes. Pool and Ledger service refactor.

- Directory.Build.props
- src/Hyperledger.Aries/Agents/DefaultAgent.cs
- src/Hyperledger.Aries/Features/IssueCredential/Models/CredentialPreviewAttributeConverter.cs
- src/Hyperledger.Aries/Utils/CredentialUtils.cs
- test/Hyperledger.Aries.Tests/ConverterTests.cs
- test/Hyperledger.Aries.Tests/Protocols/CredentialUtilsTests.cs
Modify the expectation that `mime-type` won't be supplied with credential attribute and may be null. Will be treated as string as described in [Mime Type and Value](https://github.com/hyperledger/aries-rfcs/tree/master/features/0036-issue-credential#mime-type-and-value) in RFC 0036
> Credential attribute preview parsing fix

- src/Hyperledger.Aries/Features/IssueCredential/DefaultSchemaService.cs
- src/Hyperledger.Aries/Features/IssueCredential/DefaultTailsService.cs
When calling new Uri(tailsBaseUri, tailsfile) when the tailsBaseUri had some additional query parameters, these parameters got lost.
Changed new Uri(tailsBaseUri, tailsfile) to new Uri(tailsBaseUri + tailsfile).
**Fixes**: 
Now all query parameters stay in the tailsLocation.
> Fix of tailsLocation issue with query parameters

- src/Hyperledger.Aries/Features/PresentProof/Models/RequestedProof.cs
Getting an error parsing a Proof when self attested attributes are set. The value of a self attested attribute in a requested_proof should parse to the string type.
[JSON format reference](https://github.com/hyperledger/indy-sdk/blob/master/libindy/src/api/anoncreds.rs#L2102)
- Changing the type of the SelfAttestedAttributes property from `Dictionary<string, ProofAttribute>` to `Dictionary<string, string>`
> Changing self attested attribute value type to string

- src/Hyperledger.Aries.Routing.Mediator/Handlers/MediatorForwardHandler.cs
- src/Hyperledger.Aries/Features/Routing/DefaultForwardHandler.cs
- src/Hyperledger.Aries/Features/Routing/ForwardMessage.cs
- src/Hyperledger.Aries/Utils/CryptoUtils.cs
- test/Hyperledger.Aries.Tests/MessageServiceTests.cs
Reverting forward change for now. Will add later when mobile implementations are in production.
> Update forward message format based on RFC. Mediator middleware fix (#37)

- docs/xamarin.rst
- samples/xamarin-forms/AFMobileSample.Android/AFMobileSample.Android.csproj
- samples/xamarin-forms/AFMobileSample.Android/MainActivity.cs
Android NDK >= 18 uses LLVM and libindy >= 1.12.0 has been built using the LLVM toolchain.
This PR updates the documentation and sample code to use `libc++_shared.so` which is compatible with the latest version of libindy and Android NDK.
> Xamarin: Update instructions for including latest libindy

- src/Hyperledger.Aries.Routing.Mediator/Handlers/MediatorForwardHandler.cs
Fixes the `InboxItemEvent` to have the `Item`'s Id instead of the `Inbox` Id which is already represented in the `InboxId` field.
> MediatorForwardHandler: Refer to ItemRecord Id instead of InboxId

- src/Hyperledger.Aries.AspNetCore/AgentMiddleware.cs
SignalR .NET clients sends an empty content-type while initiating a connection and it breaks the
middleware.
P.S. I thought about sending a PR for this upstream but a request to get this fixed in the .NET client wasn't accepted before: https://github.com/SignalR/SignalR/issues/3639.
Added a null check for `Request.ContentType`
> AspNetCore: Add null conditional for content-type check

- src/Hyperledger.Aries/Utils/Base64UrlEncoder.cs
Related issues across Aries repos
https://github.com/hyperledger/aries-rfcs/issues/290
https://github.com/hyperledger/aries-protocol-test-suite/issues/26
> Always use base64 padding

- src/Hyperledger.Aries/Features/PresentProof/Models/ProofPredicateInfo.cs
Now, it's getting the parsing error when you create presentation if predicates are set in the proof request. The p_value of the predicate info should parse to the int type. (The Indy SDK supports only numeric comparisons for predicates)
- Changing the type of the PredicateValue from string to int
> Changing the type of the PredicateValue in ProofPredicateInfo to int

- src/Hyperledger.Aries.Routing.Mediator/Handlers/RoutingInboxHandler.cs
Allows edge agents to call device registration multiple times, without throwing.
> Allow multiple registrations of device without throwing

- Directory.Build.props
- src/Hyperledger.Aries/Features/IssueCredential/DefaultCredentialService.cs
- test/Hyperledger.Aries.Tests/Protocols/CredentialTransientTests.cs
This PR resolves the issue where the Credential Attributes were set explicitly to null when receiving a connectionless credential
- Remove the explicitly null set value
- Update test case that covers the flow
**Fixes**: #
- DefaultCredentialService
- CredentialTransientTest
> [FIX] connectionless credential offer | fixing the procedure to store a connectionless credential offer

- src/Hyperledger.Aries/Features/IssueCredential/Abstractions/ISchemaService.cs
- src/Hyperledger.Aries/Features/IssueCredential/Abstractions/ITailsService.cs
- src/Hyperledger.Aries/Features/IssueCredential/DefaultCredentialService.cs
- src/Hyperledger.Aries/Features/IssueCredential/DefaultSchemaService.cs
- src/Hyperledger.Aries/Features/IssueCredential/DefaultTailsService.cs
- src/Hyperledger.Aries/Features/PresentProof/DefaultProofService.cs
- src/Hyperledger.Aries/Ledger/Abstractions/ILedgerService.cs
- src/Hyperledger.Aries/Ledger/DefaultLedgerService.cs
- test/Hyperledger.Aries.Tests/Payments/PaymentTests.cs
- test/Hyperledger.Aries.Tests/SchemaServiceTests.cs
Signed-off-by: Tomislav Markovski <tomislav@streetcred.id>
This PR fixes an inconsistency in the use of AgentContext to pass the Pool parameter. Now all service method signatures use `IAgentContext` and call the Pool as needed internally.
This is a minor breaking change only for those who implement custom `ILedgerService`, `ISchemaService` or `ITailsService`
> Consoldate the use of AgentContext over Pool

- .editorconfig
- src/Hyperledger.Aries.Routing.Edge/AriesFrameworkBuilderExtensions.cs
- src/Hyperledger.Aries.Routing.Edge/EdgeClientService.cs
- src/Hyperledger.Aries.TestHarness/Scenarios.cs
- src/Hyperledger.Aries/Features/PresentProof/IProofService.cs
- src/Hyperledger.Aries/Features/PresentProof/Messages/PresentationPreview.cs
- test/.editorconfig
Eliminate compiler warnings.
Changed the Missing XML comment from a warning to a suggestion.
Suppress the warning about calling obsolete in tests.  We still have to test them until removed.
Fixed some XML comments that had missing or incorrect parameters.
Removed unused param.
Replaced 1 obsolete function call with the recommended replacement.
Currently builds with no warnings.
> Clean up compiler warnings 

- src/Hyperledger.Aries.Routing/CreateInboxResponseMessage.cs
`CreateInboxResponseMessage` does not have `@id` and `@type` agent message properties set. This can cause issues for a generic agent message handler that uses `@type` for delegating message handling to a specific handler.
- Set random ID and correct type from `RoutingTypeNames` in `CreateInboxResponseMessage` constructor
**Fixes**: #
Would it also make sense to add a thread decorator referring back to the initial `CreateInboxMessage`? That would be more in line with Aries RFCs, but creating an inbox is generally using duplex communication, so it seems redundant.
> Set id and type for CreateInboxResponseMessage

- src/Hyperledger.Aries/Features/IssueCredential/DefaultCredentialService.cs
Signed-off-by: Narankhuu Boldbaatar <narankhuu.b@gmail.com>
To make public process* functions of default credential service extendable.
- To add the virtual keyword to a few function declarations.
> Make few functions extendable with virtual keywords

- src/Hyperledger.Aries/Features/DidExchange/DefaultConnectionService.cs
- src/Hyperledger.Aries/Features/DidExchange/IConnectionService.cs
- src/Hyperledger.Aries/Features/IssueCredential/Abstractions/ICredentialService.cs
- src/Hyperledger.Aries/Features/IssueCredential/DefaultCredentialService.cs
- src/Hyperledger.Aries/Storage/DefaultWalletRecordService.cs
- src/Hyperledger.Aries/Storage/IWalletRecordService.cs
- test/Hyperledger.Aries.Tests/MessageServiceTests.cs
- test/Hyperledger.Aries.Tests/MockExtendedConnectionService.cs
Add simple pagination in the `DefaultWalletRecordService`
- add `skip` parameter to the `SearchAsync` method
> Add pagination support for SearchAsync

- Directory.Build.props
- src/Hyperledger.Aries/Features/IssueCredential/DefaultCredentialService.cs
- src/Hyperledger.Aries/Features/PresentProof/DefaultProofService.cs
- src/Hyperledger.Aries/Features/PresentProof/IProofService.cs
Add a method in proof service that checks if a credential has been revoked. Can be used by a holder of a credential.
> Check if a credential is revoked against the ledger state

- src/Hyperledger.Aries/Features/PresentProof/DefaultProofService.cs
Signed-off-by: Sebastian Bickerle <sebastian.bickerle@main-incubator.com>
Removes the filtering of non-revocable credentials from proof requests with a NonRevoked interval
This allows proof requests with a NonRevoked interval to be answered with revocable and non-revocable credentials as it is supported by indy
- Remove the where clause from the default ListCredentialsForProofRequestAsync method
> Removed filter for non-revocable creds in ListCredentialsForProofRequest

- src/Hyperledger.Aries.Routing.Mediator/Handlers/RoutingInboxHandler.cs
- test/Hyperledger.Aries.Tests/Routing/RoutingInboxHandlerTests.cs
We added support for saving metadata dictionary values on mediator inboxRecord.
- MetaData object is of type  `Dictionary<string, string>` therefore it can be stored under `Tags` property on inbox record
- Unit tests were created for both flows - with and without `MetaData`
**Fixes**: #
> Adding support for metadata with inbox creation

- Directory.Build.props
- src/Hyperledger.Aries.Routing.Mediator/Handlers/RoutingInboxHandler.cs
- src/Hyperledger.Aries/Storage/Models/WalletStorageConfiguration.cs
- test/Hyperledger.Aries.Tests/Routing/RoutingInboxHandlerTests.cs
- test/Hyperledger.Aries.Tests/Storage/Models/WalletStorageConfigurationTest.cs
Add support for storing inbox records using the Postgres storage plugin on the Mediator agent.
- Propagate storage credentials and storage configuration used for the storage plugins.
- Bump NuGet package version.
- Unit tests for the case when credentials and configuration options are set.
- Expand WalletStorageConfiguration so that values don't get removed inside recordService.AddAsync(agentContext.Wallet, inboxRecord) call.
**Fixes**: #
> Add support for using PostgreSQL database for storing mediator agent inbox records

- Directory.Build.props
- src/Hyperledger.Aries.Routing.Mediator/Handlers/RoutingInboxHandler.cs
- test/Hyperledger.Aries.Tests/Routing/RoutingInboxHandlerTests.cs
- test/Hyperledger.Aries.Tests/WalletTests.cs
- The default mode to derive wallet key is via an algorithm argon2 which is very CPU and memory consuming. In order to minimize resource usage, we added support for RAW key derivation since safe storage of the wallet keys can be provided.
- Add an ability to provide a custom key derivation method.
- Generate wallet key using secure generator provided in the indy-sdk. Generated wallet key is suitable for the "RAW" derivation method.
- Test that wallet with described parameters can be successfully created.
**Fixes**: #
> Add support for RAW key derivation on inbox wallet create

- Directory.Build.props
- src/Hyperledger.Aries/Features/IssueCredential/DefaultCredentialService.cs
- src/Hyperledger.Aries/Features/IssueCredential/Records/CredentialRecord.cs
This PR reduces the size of the Value column for the record persistence by moving large fields like OfferJson and RequestJson to tags. Tags are persisted in separate columns in the underlying storage.
> Optimize storage size, when saving credential record data

- docs/docker.rst
- docs/gettingstarted.rst
Signed-off-by: Stephen Curran <swcurran@gmail.com>
There are some references in the repo to the old "streetcred-id" GitHub organization that need to be changed to "trinsic-id".  Another party has grabbed the "streetcred-id" github account and is using it, so the links are no longer reliable.
- Rename several paths into GitHub to use Trinsic
**Fixes**: #
> Change references to streetcred-id GitHub org to trinsic-id

- src/Hyperledger.Aries/Features/PresentProof/DefaultProofService.cs
- src/Hyperledger.Aries/Features/PresentProof/Models/RevocationInterval.cs
- test/Hyperledger.Aries.Tests/Protocols/RevocationTests.cs
**Short description of what this resolves:**
Added support for proof request with non revoked on attribute level.
**Changes proposed in this pull request:**
Adjusted "BuildRevocationStatesAsync" function of "DefaultProofService".
Adjusted test in "RevocationTests"
**Fixes**: #
> Support non revoked on attribute level

- src/Hyperledger.Aries/Features/IssueCredential/DefaultCredentialHandler.cs
Mime-type for issued credentials was hard coded in UpdateValues() to text/plain, which caused every credential in the wallet to have text/plain as the mimetype. This PR resolves that issue.
Changed UpdateValues() in DefaultCredentialHandler
> Support img png mimetype

- src/Hyperledger.Aries/Features/PresentProof/DefaultProofService.cs
Signed-off-by: Dindexx <kevin.dinh@main-incubator.com>
Issue where a proof that consists of a combination of attributes with checks for NonRevoked and attributes without checks for NonRevoked couldnt be processed.
Dont build revocation state for attributes where NonRevoked was not set
> DefaulProofService BuildRevocationStatesFix

- src/Hyperledger.Aries/Features/Handshakes/Connection/DefaultConnectionService.cs
- src/Hyperledger.Aries/Features/Handshakes/DidExchange/DefaultDidExchangeService.cs
- src/Hyperledger.Aries/Features/IssueCredential/DefaultCredentialService.cs
- src/Hyperledger.Aries/Features/IssueCredential/DefaultSchemaService.cs
- src/Hyperledger.Aries/Features/PresentProof/DefaultProofService.cs
- src/Hyperledger.Aries/Ledger/DefaultLedgerService.cs
- src/Hyperledger.Aries/Ledger/DefaultLedgerSigningService.cs
- src/Hyperledger.Aries/Ledger/DefaultPoolService.cs
- src/Hyperledger.Aries/Payments/DefaultPaymentService.cs
- src/Hyperledger.Aries/Signatures/DefaultSigningService.cs
Signed-off-by: Sebastian Bickerle <sebastian.bickerle@main-incubator.com>
This PR adds the virtual modifier to all public methods of default services where it was missing. It enables custom services to override the default behaviour or add a custom behaviour. All public methods of default services should have the virtual modifier by default.
- Adds virtual modifier to all public methods of default services
> Add virtual modifier to all public methods of default services
