src/AgentFramework.Core.Handlers/Internal/DefaultConnectionHandler.cs
=> Assign context record object in connection handler

Directory.Build.props
=> Version update to 4.0.2

docker/indy-pool.dockerfile, src/AgentFramework.Core.Handlers/Internal/DefaultProofHandler.cs
=> Add proof object as context record in handler

Directory.Build.props, src/AgentFramework.Core.Handlers/Internal/DefaultCredentialHandler.cs, src/AgentFramework.Core/Contracts/ICredentialService.cs, src/AgentFramework.Core/Decorators/Attachments/Attachment.cs, src/AgentFramework.Core/Decorators/Attachments/AttachmentContent.cs, src/AgentFramework.Core/Messages/Credentials/CredentialPreviewMessage.cs, src/AgentFramework.Core/Messages/Credentials/V1/CredentialIssueMessage.cs, src/AgentFramework.Core/Messages/Credentials/V1/CredentialOfferMessage.cs, src/AgentFramework.Core/Messages/Credentials/V1/CredentialPreviewMessage.cs, src/AgentFramework.Core/Messages/Credentials/V1/CredentialProposalMessage.cs, src/AgentFramework.Core/Messages/Credentials/V1/CredentialRequestMessage.cs, src/AgentFramework.Core/Messages/MessageTypes.cs, src/AgentFramework.Core/Models/Credentials/CredentialMimeTypes.cs, src/AgentFramework.Core/Runtime/DefaultCredentialService.cs, src/AgentFramework.Core/Runtime/DefaultCredentialServiceV1.cs, src/AgentFramework.TestHarness/Mock/InProcAgent.cs, src/AgentFramework.TestHarness/TestSingleWallet.cs, test/AgentFramework.Core.Tests/Protocols/CredentialV1Tests.cs
Implements Credential Issuance RFC v1.0
https://github.com/hyperledger/aries-rfcs/tree/master/features/0036-issue-credential
- Add protocol implementation alongside old protocol version for backwards compatibility
- Mark old implementation as Obsolete
=> Issue Credential Protocol 1.0

Directory.Build.props, src/AgentFramework.Core/Contracts/ILedgerService.cs, src/AgentFramework.Core/Models/Ledger/IndyAml.cs, src/AgentFramework.Core/Runtime/DefaultLedgerService.cs, test/AgentFramework.Core.Tests/LerdgerTests.cs
=> Added LookupAmlAsync to Ledger Service

Directory.Build.props, src/AgentFramework.Core.Handlers/AgentFramework.Core.Handlers.csproj, src/AgentFramework.Core.Handlers/AgentFrameworkBuilderExtensions.cs, src/AgentFramework.Core.Handlers/Hosting/DefaultProvisioningHostedService.cs, src/AgentFramework.Core.Handlers/Hosting/IssuerProvisioningHostedService.cs, src/AgentFramework.Core/AgentFramework.Core.csproj, src/AgentFramework.Core/Configuration/PoolConfigurationHostedService.cs, src/AgentFramework.Core/Configuration/ServiceCollectionExtensions.cs, src/AgentFramework.Core/Models/Records/ProvisioningRecord.cs, src/AgentFramework.Core/Models/Wallets/IssuerProvisioningConfiguration.cs
Adds a more flexible agent configuration system, for issuer and non-issuer agents.
Leverages the .NET Core Hosting model.
Many existing configuration methods marked as Obsolete, to indicate they will be removed in a future major release.
=> Configuration and extensions added using Hosting services

src/Hyperledger.Aries.Routing.Edge/EdgeProvisioningService.cs, src/Hyperledger.Aries.Routing.Mediator/MediatorProvisioningService.cs
=> Capture non-fatal exception

src/Hyperledger.Aries/Features/IssueCredential/DefaultTailsService.cs
Improved handling of tails files.
CheckTailsFile edited for better handling of tails file checking and loading.
**Fixes**: 
URIs with parameters caused some issues.
=> using tailsHash for tailsfilename, check for directory existence

Directory.Build.props, src/Hyperledger.Aries/Configuration/DefaultProvisioningService.cs, src/Hyperledger.Aries/Features/IssueCredential/DefaultSchemaService.cs
=> Add tails endpoint URI

src/Hyperledger.Aries/Features/PresentProof/DefaultProofService.cs
=> Allow sending message with non-existent routing keys

Directory.Build.props, src/Hyperledger.Aries.AspNetCore/AgentMiddleware.cs, src/Hyperledger.Aries.AspNetCore/ApplicationBuilderExtensions.cs, test/Hyperledger.Aries.Tests/ConfigurationTests.cs
=> Aspnetcore middleware registration pipeline failed to construct instance

Directory.Build.props, src/Hyperledger.Aries.Routing.Mediator/AriesFrameworkBuilderExtensions.cs, src/Hyperledger.Aries.Routing.Mediator/Handlers/MediatorForwardHandler.cs, src/Hyperledger.Aries/Agents/Models/PackedMessageContext.cs, src/Hyperledger.Aries/Features/Routing/DefaultForwardHandler.cs, src/Hyperledger.Aries/Features/Routing/ForwardMessage.cs, src/Hyperledger.Aries/Utils/CryptoUtils.cs, test/Hyperledger.Aries.Tests/MessageServiceTests.cs
Updates Forward message according to RFC https://github.com/hyperledger/aries-rfcs/tree/master/concepts/0094-cross-domain-messaging
Aligns with https://github.com/hyperledger/aries-cloudagent-python/pull/240
Fixes #35 
=> Update forward message format based on RFC. Mediator middleware fix

src/Hyperledger.Aries/Features/IssueCredential/DefaultCredentialHandler.cs, test/Hyperledger.Aries.Tests/SchemaServiceTests.cs
Updates the credential handler to extract the raw values when credential is issued.
This helps with showing human readable values in the UI.
=> Extract credential values from incoming issued credential

Directory.Build.props, src/Hyperledger.Aries/Storage/DefaultWalletRecordService.cs
=> Pass deserializer settings to record service

Directory.Build.props, src/Hyperledger.Aries.Routing.Edge/EdgeClientService.Backup.cs, src/Hyperledger.Aries.Routing.Edge/EdgeClientService.cs
=> Use WalletService in restore backup method

Directory.Build.props, src/Hyperledger.Aries.TestHarness/Mock/InProcAgent.cs, src/Hyperledger.Aries.TestHarness/Mock/InProcMessageHandler.cs, src/Hyperledger.Aries.TestHarness/TestSingleWallet.cs, src/Hyperledger.Aries/Common/ErrorCode.cs, src/Hyperledger.Aries/Features/IssueCredential/DefaultSchemaService.cs, src/Hyperledger.Aries/Features/IssueCredential/DefaultTailsService.cs, src/Hyperledger.Aries/Features/IssueCredential/Models/CredentialInfo.cs, src/Hyperledger.Aries/Features/PresentProof/DefaultProofService.cs, src/Hyperledger.Aries/Features/PresentProof/Models/ProofIdentifier.cs, src/Hyperledger.Aries/Ledger/DefaultLedgerService.cs, test/Hyperledger.Aries.Tests/Payments/PaymentTests.cs, test/Hyperledger.Aries.Tests/Payments/ProtocolTests.cs, test/Hyperledger.Aries.Tests/Payments/TransferTests.cs, test/Hyperledger.Aries.Tests/Protocols/RevocationTests.cs
=> Remove sovrin token tests. Update verification to check revocation interval

Directory.Build.props, src/Hyperledger.Aries.Routing.Edge/EdgeClientService.Backup.cs, src/Hyperledger.Aries.Routing.Edge/IEdgeClientService.cs, src/Hyperledger.Aries.Routing.Mediator/Handlers/RetrieveBackupHandler.cs, src/Hyperledger.Aries.Routing.Mediator/Storage/DefaultStorageService.cs, src/Hyperledger.Aries.Routing.Mediator/Storage/IStorageService.cs, src/Hyperledger.Aries.Routing/ListBackupsResponseAgentMessage.cs
=> Correct the folder timestamp logic when retrieving backup

Directory.Build.props, src/Hyperledger.Aries.Routing.Mediator/Storage/DefaultStorageService.cs, src/Hyperledger.Aries/Features/IssueCredential/DefaultTailsService.cs
=> Check if tails file is present instead download everytime

Directory.Build.props, src/Hyperledger.Aries/Features/PresentProof/DefaultProofService.cs, src/Hyperledger.Aries/Features/PresentProof/IProofService.cs, src/Hyperledger.Aries/Features/PresentProof/Models/RevocationInterval.cs, test/Hyperledger.Aries.Tests/Protocols/RevocationTests.cs
=> Proof service returns only relevant credentials with respect to revocation proof

samples/aspnetcore/Controllers/ConnectionsController.cs, samples/aspnetcore/Controllers/CredentialsController.cs, samples/aspnetcore/Models/CredentialFormModel.cs, samples/aspnetcore/Models/CredentialOfferModel.cs, samples/aspnetcore/Models/CredentialViewModel.cs, samples/aspnetcore/Startup.cs, samples/aspnetcore/Views/Credentials/CredentialsForm.cshtml, samples/aspnetcore/Views/Credentials/Index.cshtml, samples/aspnetcore/Views/Shared/_Layout.cshtml
Add credential issuance scenarios to samples/aspnetcore
- we can issue credentials in the sample
- we can view the issued credentials
I used some code snippets from https://github.com/hyperledger/aries-acapy-controllers/tree/master/AliceFaberAcmeDemo/controllers/faber-controller
=> Add credential issuance scenarios

Directory.Build.props, src/Hyperledger.Aries/Features/PresentProof/DefaultProofService.cs
Signed-off-by: Tomislav Markovski <tomislav@streetcred.id>
=> Correct thread id logic for presentation response

Directory.Build.props, src/Hyperledger.Aries.TestHarness/Scenarios.cs, src/Hyperledger.Aries.sln, src/Hyperledger.Aries/Features/PresentProof/DefaultProofService.cs, src/Hyperledger.Aries/Features/PresentProof/Models/ProofRequest.cs
**Fixes**: #
- predicate name was not created
- initial state of proposed proof record should be proposed
=> fixed predicate name drop and initial proposed state in propose verifications

Directory.Build.props, src/Hyperledger.Aries.TestHarness/Scenarios.cs, src/Hyperledger.Aries/Features/PresentProof/DefaultProofService.cs
- Fixes serialization of proof proposal
- version bump to 1.2.14
=> fixed serialization of proof proposal

.editorconfig
Utlize editorconfig capabilities to maintain consistent formatting across the repo.
=> Add starter .editorconfig

src/Hyperledger.Aries/Configuration/DefaultProvisioningService.cs, src/Hyperledger.Aries/Configuration/IProvisioningService.cs, src/Hyperledger.Aries/Ledger/Models/IndyTaaAcceptance.cs
Added taa acceptance mechanism.
* add `AcceptanceMechanism` in the `IndyTaaAgreement`
* add `acceptanceMechanism` param to the `AcceptTxnAuthorAgreementAsync` function
=> Add acceptance mechanism to the IndyTaaAcceptance model

src/Hyperledger.Aries/Agents/MessageHandlerBase.cs, src/Hyperledger.Aries/Agents/MessageTypesHttps.cs, src/Hyperledger.Aries/Features/BasicMessage/DefaultBasicMessageHandler.cs, src/Hyperledger.Aries/Features/DidExchange/DefaultConnectionHandler.cs, src/Hyperledger.Aries/Features/Discovery/DefaultDiscoveryHandler.cs, src/Hyperledger.Aries/Features/IssueCredential/DefaultCredentialHandler.cs, src/Hyperledger.Aries/Features/PresentProof/DefaultProofHandler.cs, src/Hyperledger.Aries/Features/Routing/DefaultForwardHandler.cs, src/Hyperledger.Aries/Features/TrustPing/DefaultTrustPingHandler.cs, src/Hyperledger.Aries/Utils/MessageUtils.cs
=> Update message types to use https in addition to old type

Directory.Build.props, src/Hyperledger.Aries/Common/AgentFrameworkException.cs, src/Hyperledger.Aries/Common/ErrorCode.cs, src/Hyperledger.Aries/Features/IssueCredential/DefaultCredentialService.cs
- It propagates the credentialId to an Indy Exception of wrong ledger.
- Introducing InvalidLedger in ErrorCodes
- New AriesFrameworkException constructor
**Fixes**: #
=> Propagate exception to contain credential Record ID

src/Hyperledger.Aries.Routing.Mediator/MediatorAgent.cs
=> Add discovery and trust ping handler to default mediator configuration

src/Hyperledger.Aries/Features/PresentProof/DefaultProofService.cs
Signed-off-by: Narankhuu Boldbaatar <narankhuu.b@gmail.com>
To make public functions of default proof service extendable.
- To add the virtual keyword to a few function declarations.
- To move public functions out of the so-called private methods region.
=> Make few functions extendable with virtual keywords

Directory.Build.props, samples/blazorHosted/Directory.Build.props, samples/routing/MediatorAgentService/Mediator.Web.csproj, src/Hyperledger.Aries.AspNetCore/Hyperledger.Aries.AspNetCore.csproj, src/Hyperledger.Aries.Routing.Mediator/AriesFrameworkBuilderExtensions.cs, src/Hyperledger.Aries.Routing.Mediator/Hyperledger.Aries.Routing.Mediator.csproj, src/Hyperledger.Aries.TestHarness/Hyperledger.Aries.TestHarness.csproj, src/Hyperledger.Aries/Features/IssueCredential/DefaultCredentialService.cs
Update fluent validation to 9.2.0.
=> Update fluent_validation to 9.2.0.

.travis.yml
Removing travis.ci integration per #148
=> Remove travis.ci integration

samples/aspnetcore/Controllers/ConnectionsController.cs, samples/aspnetcore/Controllers/CredentialsController.cs
* Fix build errors in WebAgent sample due to previous MessageTypeHttps PR
Signed-off-by: Ajay Jadhav <jadhavajay@gmail.com>
build errors in WebAgent sample
=> Fix build errors in WebAgent sample

src/Hyperledger.Aries/Configuration/DefaultProvisioningService.cs
=> Allow overrides on ProvisionAgentAsync

src/Hyperledger.Aries/Utils/CryptoUtils.cs
=> Make CryptoUtils public

Directory.Build.props, src/Hyperledger.Aries/Features/PresentProof/DefaultProofService.cs, test/Hyperledger.Aries.Tests/Protocols/RevocationTests.cs
Signed-off-by: Tomislav Markovski <tomislav@trinsic.id>
=> ProofRequest missing parameters for revocation check

Directory.Build.props, src/Hyperledger.Aries/Agents/Models/MessageContext.cs
Signed-off-by: Tomislav Markovski <tomislav@trinsic.id>
=> Allow setting the connection record in message context

src/Hyperledger.Aries/Features/IssueCredential/DefaultCredentialService.cs
The error message currently does not reflect the condition being checked
=> Error message was incorrect.

src/Hyperledger.Aries.Routing.Edge/EdgeClientService.cs, src/Hyperledger.Aries.Routing.Edge/IEdgeClientService.cs, src/Hyperledger.Aries.Routing.Mediator/Handlers/RoutingInboxHandler.cs, src/Hyperledger.Aries.Routing/RoutingTypeNames.cs, src/Hyperledger.Aries.Routing/UpsertDeviceInfoMessage.cs, src/Hyperledger.Aries/Features/BasicMessage/DefaultBasicMessageService.cs, src/Hyperledger.Aries/Features/BasicMessage/IBasicMessageService.cs
Adds support to update existing DeviceInfoRecords with an UpsertDeviceMessage.
- Adds support to update existing DeviceInfoRecords with an UpsertDeviceMessage.
**Fixes**: #
=> add UpsertDeviceInfoMessage
